# Generated by Django 2.2.4 on 2019-12-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapp', '0003_auto_20191006_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_pub']},
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
